services:
  db:
    image: pgvector/pgvector:pg17
    container_name: docuquery-db

    environment:
      POSTGRES_USER: docuquery
      POSTGRES_PASSWORD: docuquery
      POSTGRES_DB: docuquery

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: